[package]
name = "game_camera"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true, features = ["bevy_state"] }
game_player = { workspace = true }

game_action = { workspace = true }
